[build]
nixPkgs = ["yt-dlp", "ffmpeg", "python311"]

[phases.setup]
commands = [
    "python -m pip install --upgrade yt-dlp",
    "ln -sf $(which yt-dlp) /usr/bin/yt-dlp || true",
    "yt-dlp --version"
]

